apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: banka-2-dev
  labels:
    service: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: notification-service
  template:
    metadata:
      labels:
        service: notification-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-2/notification-service:latest
          imagePullPolicy: Always
          name: notification-service
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://banka-2-ha:5432/bank_db?currentSchema=notification_service_schema
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: banka-2-pguser-admin
                  key: user
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: banka-2-pguser-admin
                  key: password
            - name: spring.rabbitmq.username
              value: user
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: spring.jpa.hibernate.ddl-auto
              value: update
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: banka-2-dev
spec:
  selector:
    service: notification-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002