apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  namespace: {{ .Release.Namespace }}
  labels:
    service: bank-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bank-service
  template:
    metadata:
      labels:
        service: bank-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-2/bank-service:{{ .Values.imageTag }}
          imagePullPolicy: Always
          name: bank-service
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://banka-2-ha:5432/bank_db?currentSchema=bank_service_schema
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: banka-2-pguser-admin
                  key: user
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: banka-2-pguser-admin
                  key: password
            - name: spring.rabbitmq.username
              value: user
            - name: spring.rabbitmq.host
              value: {{ .Release.Name }}-rabbitmq
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
            - name: spring.jpa.hibernate.ddl-auto
              value: update
            - name: SPRING_PROFILES_ACTIVE
              value: dev

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    service: bank-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003